### ISSUE TITLE
Downscalin CMIP6 climate data

### ISSUE THREAD

**Issue by Abebemengistu** [carbonplan/cmip6-downscaling#319] opened 2023-09-21 16:19 UTC
I am a Beginner and I don't know how to work on GitHub, could you help me with how to follow from scratch?
Regards!

**Comment by maxrjones** [comment] 2024-01-31 18:54
closing as a duplicate of https://github.com/carbonplan/cmip6-downscaling/issues/320

**Closed by maxrjones** 2024-01-31 18:54 UTC
